Repository kubevirt-ui/kubevirt-components, pull requests merged in 2022-02, with the labels that each got.

#8 Github Pages doc fix
  .github/workflows/styleguide.yml
Labels: size/XS

#10 Typescript props on styleguide docs
  package.json
  styleguide.config.js
  yarn.lock
Labels: size/XS

#11 Publish conditions
  .github/workflows/deploy.yml
Labels: size/XS, approved, lgtm

#12 Doc style
  jest-setup.ts
  jest.config.ts
  package.json
  styleguide.config.js
  styleguide/components/Logo/index.tsx
  styleguide/components/Logo/logo.png
  styleguide/favicon-32x32.png
  styleguide/global.d.ts
  styleguide/styles.ts
  styleguide/theme.ts
  webpack.config.js
  yarn.lock
Labels: size/L, approved, lgtm

#13 Doc style fix
  styleguide/components/Logo/index.tsx
Labels: size/XS, approved, lgtm

#14 Doc style fix 2
  .github/workflows/styleguide.yml
  styleguide/styles.ts
Labels: size/M, approved, lgtm

#15 I swear it's the last time
  styleguide/components/Logo/index.tsx
  styleguide/styles.ts
  styleguide/theme.ts
  tsconfig.json
Labels: size/M, approved, lgtm

#16 Doc new style
  package.json
  src/components/Button/Button.md
  src/components/Button/Button.test.tsx
  src/components/Button/Button.tsx
  src/components/Button/__snapshots__/Button.test.tsx.snap
  src/components/VMStatusConditionLabel/VMStatusConditionLabel.md
  src/components/VMStatusConditionLabel/VMStatusConditionLabel.tsx
  src/components/VMStatusConditionLabel/tests/VMStatusConditionLabel.test.tsx
  src/components/VMStatusConditionLabel/tests/__snapshots__/VMStatusConditionLabel.test.tsx.snap
  src/components/VMStatusConditionLabel/tests/mocks.ts
  src/components/VMStatusConditionLabelList/VMStatusConditionLabelList.md
  src/components/VMStatusConditionLabelList/VMStatusConditionLabelList.tsx
  src/components/VMStatusConditionLabelList/tests/VMStatusConditionLabelList.test.tsx
  src/components/VMStatusConditionLabelList/tests/__snapshots__/VMStatusConditionLabelList.test.tsx.snap
  src/components/VMStatusConditionLabelList/tests/mocks.ts
  src/components/index.ts
  styleguide.config.js
  styleguide/components/Logo.tsx
  styleguide/components/Logo/logo.png
  styleguide/components/StyleGuideRenderer.tsx
  styleguide/components/Type.tsx
  styleguide/global.d.ts
  styleguide/logo.png
  styleguide/styles.ts
  styleguide/theme.ts
  styleguide/webpack.config.js
  yarn.lock
Labels: size/XL, approved, lgtm

#18 Add bridge
  .eslintignore
  bridge/environment.sh
  bridge/index.js
  bridge/package.json
  bridge/yarn.lock
  jest.config.ts
  package.json
  src/components/icons/README.md
  src/components/index.ts
  src/components/status/VMStatusConditionLabel/VMStatusConditionLabel.md
  src/components/status/VMStatusConditionLabel/VMStatusConditionLabel.tsx
  src/components/status/VMStatusConditionLabel/index.ts
  src/components/status/VMStatusConditionLabel/tests/VMStatusConditionLabel.test.tsx
  src/components/status/VMStatusConditionLabel/tests/__snapshots__/VMStatusConditionLabel.test.tsx.snap
  src/components/status/VMStatusConditionLabel/tests/mocks.ts
  src/components/status/VMStatusConditionLabelList/VMStatusConditionLabelList.md
  src/components/status/VMStatusConditionLabelList/VMStatusConditionLabelList.tsx
  src/components/status/VMStatusConditionLabelList/index.ts
  src/components/status/VMStatusConditionLabelList/tests/VMStatusConditionLabelList.test.tsx
  src/components/status/VMStatusConditionLabelList/tests/__snapshots__/VMStatusConditionLabelList.test.tsx.snap
  src/components/status/VMStatusConditionLabelList/tests/mocks.ts
  src/components/status/index.ts
  styleguide.config.js
  tsconfig.json
  yarn.lock
Labels: size/XL, approved, lgtm

#17 VmIconStatus
  jest.config.ts
  package.json
  src/components/status/VMIconStatus/VMIconStatus.md
  src/components/status/VMIconStatus/VMIconStatus.tsx
  src/components/status/VMIconStatus/VMIconoStatus.spec.tsx
  src/components/status/VMIconStatus/__snapshots__/VMIconoStatus.spec.tsx.snap
  src/components/status/VMStatusConditionLabelList/VMStatusConditionLabelList.tsx
  styleguide/components/StyleGuideRenderer.tsx
  styleguide/styles.ts
Labels: size/XL, approved, lgtm

#20 Fix bridge typos
  bridge/environment.sh
  bridge/index.js
Labels: approved, lgtm

#29 fail test
  .github/workflows/pr_labeler.yml
  src/components/status/ConditionLabel/ConditionLabel.test.tsx
Labels: approved, lgtm

#32 fix rollup
  rollup.config.js
Labels: size/XS

#31 Sections readme
  src/components/icons/README.md
  src/components/shims/README.md
  src/components/status/README.md
  styleguide.config.js
  styleguide/styles.ts
Labels: size/S, approved, lgtm

#33 Styleguidist General Style
  src/components/icons/VMIconStatus/VMIconStatus.md
  src/components/icons/VMIconStatus/VMIconStatus.tsx
  src/components/icons/VMIconStatus/VMIconoStatus.spec.tsx
  src/components/icons/VMIconStatus/__snapshots__/VMIconoStatus.spec.tsx.snap
  styleguide/components/StyleGuideRenderer.tsx
  styleguide/styles.ts
  styleguide/theme.ts
Labels: size/S, approved, lgtm

#36 bump console sdk version
  package.json
  yarn.lock
Labels: size/L, approved, lgtm

#37 rename actions
  .github/workflows/merge__build_docs.yml
  .github/workflows/pr__auto_merge.yml
  .github/workflows/pr__first_comment.yml
  .github/workflows/pr__labeler.yml
  .github/workflows/pr__unit_tests.yml
  .github/workflows/release__publish.yml
Labels: size/L, approved, lgtm

#39 Test Actions
  .github/workflows/merge__build_docs.yml
Labels: approved, lgtm

#41 Testing1234
  .github/workflows/pr__first_comment.yml
  .github/workflows/pr__labeler.yml
  README.md
Labels: approved

#42 testing
  .github/workflows/pr__first_comment.yml
  .github/workflows/pr__labeler.yml
  README.md
Labels: approved

#55 Add Random Reviewers to PRs
  .github/workflows/pr__first_comment.yml
Labels: approved, lgtm

#56 Sections Documentation
  src/components/icons/README.md
  src/components/shims/README.md
  src/components/status/README.md
  styleguide.config.js
Labels: approved, lgtm

#57 OSIcon JSDoc
  src/components/icons/OSIcon/OSIcon.md
  src/components/icons/OSIcon/OSIcon.tsx
Labels: approved, lgtm

#58 Separate docs into pages
  bridge/environment.sh
  bridge/index.js
  src/components/icons/OSIcon/OSIcon.tsx
  styleguide.config.js
  styleguide/components/StyleGuideRenderer.tsx
Labels: approved, lgtm

#61 Add octocat
  styleguide/components/StyleGuideRenderer.tsx
Labels: approved, lgtm

#60 rename vmiconstatus to statusicon
  src/components/icons/StatusIcon/StatusIcon.md
  src/components/icons/StatusIcon/StatusIcon.spec.tsx
  src/components/icons/StatusIcon/StatusIcon.tsx
  src/components/icons/StatusIcon/__snapshots__/StatusIcon.spec.tsx.snap
  src/components/icons/VMIconStatus/VMIconoStatus.spec.tsx
Labels: approved, lgtm

#62 Add reviewers automatically
  .github/workflows/pr__first_comment.yml
Labels: approved, lgtm

#63 StatusIcon showcase
  src/components/icons/StatusIcon/StatusIcon.md
  src/components/icons/StatusIcon/StatusIcon.spec.tsx
  src/components/icons/StatusIcon/StatusIcon.tsx
  src/components/icons/StatusIcon/__snapshots__/StatusIcon.spec.tsx.snap
  src/components/icons/StatusIcon/utils.ts
Labels: approved, lgtm

#64 Make octocats smaller
  README.md
  package.json
  styleguide/components/StyleGuideRenderer.tsx
Labels: approved, lgtm

#65 Favicon fix
  styleguide.config.js
  styleguide/assets/favicon-32x32.png
  styleguide/assets/logo.png
  styleguide/components/Logo.tsx
Labels: approved, lgtm

#66 This time should work
  .github/workflows/pr__first_comment.yml
  .github/workflows/pr__labeler.yml
Labels: approved, lgtm

#68 PR labeler fix
  .github/workflows/pr__labeler.yml
Labels: approved, lgtm

#67 StatusIcon Doc
  src/components/icons/StatusIcon/StatusIcon.md
  src/components/icons/StatusIcon/StatusIcon.tsx
Labels: approved, lgtm

#71 rename status
  .github/workflows/pr__labeler.yml
  package.json
  src/components/index.ts
  src/components/status/README.md
  src/components/utils/ConditionLabel/ConditionLabel.md
  src/components/utils/ConditionLabel/ConditionLabel.test.tsx
  src/components/utils/ConditionLabel/ConditionLabel.tsx
  src/components/utils/ConditionLabel/__snapshots__/ConditionLabel.test.tsx.snap
  src/components/utils/ConditionLabel/index.ts
  src/components/utils/ConditionLabel/tests/mocks.ts
  src/components/utils/ConditionLabelList/ConditionLabelList.md
  src/components/utils/ConditionLabelList/ConditionLabelList.test.tsx
  src/components/utils/ConditionLabelList/ConditionLabelList.tsx
  src/components/utils/ConditionLabelList/__snapshots__/ConditionLabelList.test.tsx.snap
  src/components/utils/ConditionLabelList/index.ts
  src/components/utils/ConditionLabelList/tests/mocks.ts
  src/components/utils/README.md
  src/components/utils/index.ts
  styleguide.config.js
  yarn.lock
Labels: approved, lgtm

#73 Add require jsdoc rule
  .eslintrc.json
  package.json
  src/components/icons/OSIcon/OSIcon.tsx
  src/components/utils/ConditionLabel/ConditionLabel.tsx
  yarn.lock
Labels: approved, lgtm

#75 Use strings for eslint rults
  .eslintrc.json
Labels: approved, lgtm

#74 Auto generate sections
  package.json
  rollup.config.js
  src/components/Icons/OSIcon/OSIcon.md
  src/components/Icons/OSIcon/OSIcon.spec.tsx
  src/components/Icons/OSIcon/OSIcon.tsx
  src/components/Icons/OSIcon/index.ts
  src/components/Icons/OSIcon/svg/bsd.svg
  src/components/Icons/OSIcon/svg/centos.svg
  src/components/Icons/OSIcon/svg/debian.svg
  src/components/Icons/OSIcon/svg/fedora.svg
  src/components/Icons/OSIcon/svg/linux.svg
  src/components/Icons/OSIcon/svg/opensuse.svg
  src/components/Icons/OSIcon/svg/rhel.svg
  src/components/Icons/OSIcon/svg/ubuntu.svg
  src/components/Icons/OSIcon/svg/windows.svg
  src/components/Icons/README.md
  src/components/Icons/StatusIcon/StatusIcon.md
  src/components/Icons/StatusIcon/StatusIcon.spec.tsx
  src/components/Icons/StatusIcon/StatusIcon.tsx
  src/components/Icons/StatusIcon/__snapshots__/StatusIcon.spec.tsx.snap
  src/components/Icons/StatusIcon/index.ts
  src/components/Icons/StatusIcon/utils.ts
  src/components/Icons/index.ts
  src/components/Shims/README.md
  src/components/Shims/index.ts
  src/components/Utils/ConditionLabel/ConditionLabel.md
  src/components/Utils/ConditionLabel/ConditionLabel.test.tsx
  src/components/Utils/ConditionLabel/ConditionLabel.tsx
  src/components/Utils/ConditionLabel/__snapshots__/ConditionLabel.test.tsx.snap
  src/components/Utils/ConditionLabel/index.ts
  src/components/Utils/ConditionLabel/tests/mocks.ts
  src/components/Utils/ConditionLabelList/ConditionLabelList.md
  src/components/Utils/ConditionLabelList/ConditionLabelList.test.tsx
  src/components/Utils/ConditionLabelList/ConditionLabelList.tsx
  src/components/Utils/ConditionLabelList/__snapshots__/ConditionLabelList.test.tsx.snap
  src/components/Utils/ConditionLabelList/index.ts
  src/components/Utils/ConditionLabelList/tests/mocks.ts
  src/components/Utils/README.md
  src/components/Utils/index.ts
  src/components/index.ts
  styleguide.config.js
  styleguide.config.proxy.js
  yarn.lock
Labels: approved, lgtm

#76 Choose only one test file pattern
  jest.config.ts
  styleguide.config.js
  styleguide.config.proxy.js
Labels: approved, lgtm
